name: AWS CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # ---------- Lambda ----------
    - name: Package Lambda
      run: |
        cd aws/pipelines/ingestion
        zip -r ingestion.zip lambda_handler.py
        mv ingestion.zip ../../terraform/lambda/

    # ---------- Docker / ECR ----------
    - name: Login to ECR
      run: |  
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
        | docker login --username AWS --password-stdin \
        ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    - name: Build & Push Docker image
      run: |
        IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest
        docker build -t $IMAGE_URI aws/pipelines/transformation
        docker push $IMAGE_URI

    # ---------- Terraform ----------
    - name: Terraform Init
      run: |
        cd aws/terraform
        terraform init

    - name: Terraform Apply
      run: |
        cd aws/terraform
        terraform apply -auto-approve
