name: GCP Terraform Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'gcp/terraform/**'
      - 'gcp/pipelines/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.3
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      
      # Package Cloud Function
      - name: Package Cloud Function
        run: |
          cd gcp/pipelines/ingestion
          zip -r function-source.zip main.py requirements.txt
      
      # Build and Push Docker Image to Artifact Registry
      - name: Build and Push Docker Image
        run: |
          cd gcp/pipelines/transformation
          
          gcloud auth configure-docker ${{ secrets.GCP_LOCATION }}-docker.pkg.dev
          
          IMAGE_URI=${{ secrets.GCP_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/multicloud-pipeline-dev-docker-repo/etl-processor:latest
          
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
      
      # Terraform
      - name: Terraform Init
        working-directory: gcp/terraform
        run: terraform init
      
      - name: Terraform Validate
        working-directory: gcp/terraform
        run: terraform validate
      
      - name: Terraform Plan
        working-directory: gcp/terraform
        run: |
          terraform plan \
            -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var="project_name=multicloud-pipeline" \
            -var="environment=dev" \
            -var="location=${{ secrets.GCP_LOCATION }}" \
            -out=tfplan
        
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: gcp/terraform
        run: |
          terraform apply -auto-approve \
            -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var="project_name=multicloud-pipeline" \
            -var="environment=dev" \
            -var="location=${{ secrets.GCP_LOCATION }}"